apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-server-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-server-demo
  template:
    metadata:
      labels:
        app: nodejs-server-demo
    spec:
      containers:
      - name: nodejs-server-demo
        image: x00192532/nodejs-server-demo
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-server-demo
spec:
  selector:
    app: nodejs-server-demo-service
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: LoadBalancer