# Define the name of the GitHub Action workflow
name: Create an EKS cluster
# This workflow is manually triggered using the GitHub Actions UI
on:
  workflow_dispatch:
    # Define inputs that are required for the manual trigger
    inputs:
      clusterName:
        description: 'Name of the EKS Cluster'
        required: true
      awsRegion:
        description: 'AWS Region for the EKS Cluster'
        required: true
      instanceType:
        description: 'AWS instance type'
        required: true
      desiredCapacity:
        description: 'Desired capacity of the EKS cluster'
        required: true
      minSize:
        description: 'Minimum size of the EKS cluster'
        required: true
      maxSize:
        description: 'Maximum size of the EKS cluster'
        required: true
      action:
        description: 'Action to perform (apply/destroy)'
        required: true

defaults:
  run:
    working-directory: aws-eks-pulumi
# Jobs to be executed in this workflow
jobs:
  # Job for applying the EKS cluster
  create_eks:
    # Use the latest Ubuntu runner
    runs-on: ubuntu-latest

    # Execute this step only if the action input is "apply"
    if: ${{ github.event.inputs.action == 'apply' }}
    # Define the steps for this job
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ github.event.inputs.awsRegion }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - run: pip install -r requirements.txt
      - uses: pulumi/actions@v6
        with:
          command: up
          stack-name: dev
          work-dir: ./aws-eks-pulumi
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          CLUSTER_NAME: ${{ github.event.inputs.clusterName }}
          INSTANCE_TYPE: ${{ github.event.inputs.instanceType }}
          CLUSTER_REGION: ${{ github.event.inputs.awsRegion }}
          DESIRED_CAPACITY: ${{ github.event.inputs.desiredCapacity }}
          MIN_SIZE: ${{ github.event.inputs.minSize }}
          MAX_SIZE: ${{ github.event.inputs.maxSize }}

  # Destroying the EKS cluster
  destroy_eks:
    runs-on: ubuntu-latest

    # Execute this job only if the action input is "destroy"
    if: ${{ github.event.inputs.action == 'destroy' }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ github.event.inputs.awsRegion }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - run: pip install -r requirements.txt
      - uses: pulumi/actions@v6
        with:
          command: destroy
          stack-name: dev
          work-dir: ./aws-eks-pulumi
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          CLUSTER_NAME: ${{ github.event.inputs.clusterName }}
          INSTANCE_TYPE: ${{ github.event.inputs.instanceType }}
          CLUSTER_REGION: ${{ github.event.inputs.awsRegion }}
          DESIRED_CAPACITY: ${{ github.event.inputs.desiredCapacity }}
          MIN_SIZE: ${{ github.event.inputs.minSize }}
          MAX_SIZE: ${{ github.event.inputs.maxSize }}
